"""Renderer: pack data → Markdown.

Markdown-first, deliberately: a pack that lives in the repository is diffable,
reviewable in a pull request, and regenerable in CI. PDF is a rendering of
this, never the source of truth.

The renderer cannot emit an unsupported sentence, because every sentence it
writes comes from a :class:`~annexiv.model.Claim`, and a Claim cannot exist
without either a citation or a gap. It also refuses outright to render a pack
whose boundary statement or gap register is missing — the same "component that
can refuse" discipline the de-identification verifier applies to its limits
page.
"""

from __future__ import annotations

from . import BOUNDARY_STATEMENT
from .model import EvidenceClass, GapKind, Pack, SectionState
from .spec import MappingSpec


class RefusalError(RuntimeError):
    """Raised instead of emitting a document that would misrepresent the run."""


_STATE_LABEL = {
    SectionState.SUPPORTED: "supported",
    SectionState.ATTESTED_ONLY: "attested only",
    SectionState.PARTIAL: "partial",
    SectionState.MISSING: "missing",
    SectionState.BY_DESIGN_GAP: "by-design gap",
}

_KIND_LABEL = {
    GapKind.ABSENT: "absent",
    GapKind.UNSIGNED: "unsigned",
    GapKind.STRUCTURALLY_INVALID: "structurally invalid",
    GapKind.BY_DESIGN: "by design — never generatable",
}


def _cite(pack: Pack, claim) -> str:
    ev = pack.evidence_by_id()
    parts = []
    for eid in claim.evidence_ids:
        r = ev[eid]
        loc = f"#{r.locator}" if r.locator else ""
        parts.append(f"[`{r.cls.value}`] `{r.source_path}{loc}` "
                     f"(`{r.source_sha256[:12]}…`, `{r.id}`) — {r.summary}")
    return parts


def render_markdown(pack: Pack, spec: MappingSpec) -> str:
    if not pack.gaps and any(s.state is SectionState.BY_DESIGN_GAP
                             for s in pack.sections):
        raise RefusalError(
            "refusing to render: a by-design gap section exists but the gap "
            "register is empty — the register is the pack's honesty mechanism "
            "and cannot be dropped")
    for section in pack.sections:
        if not section.claims:
            raise RefusalError(
                f"refusing to render: Annex IV section {section.number} carries "
                "no claims at all — every section must be populated or "
                "explicitly gap-flagged, never silently omitted")

    c = pack.completion
    app = spec.applicability
    route_date, route_label = app.route_date(pack.classification_route)

    L: list[str] = []
    L.append("# Annex IV technical documentation")
    L.append("")
    L.append(f"**Subject repository:** `{pack.repo_name}`  ")
    L.append(f"**Commit:** `{pack.repo_commit or 'not a git repository'}`  ")
    L.append(f"**Generated by:** annexiv {pack.tool_version}, mapping spec "
             f"{pack.spec_version} (`{spec.spec_sha256[:12]}…`)  ")
    L.append(f"**Regulation:** {spec.regulation['short']}, Annex IV — "
             f"{spec.regulation['annex_title']}")
    L.append("")
    L.append("> **What this document is.** " + BOUNDARY_STATEMENT)
    L.append("")

    # ── applicability ────────────────────────────────────────────────────
    L.append("## Applicability")
    L.append("")
    if route_label:
        L.append(f"Classification route declared by the provider: "
                 f"**{route_label}**. On that route the Annex IV obligation "
                 f"applies from **{route_date}**.")
    else:
        L.append("**No classification route was declared.** This tool does not "
                 "determine classification — that is the provider's regulatory "
                 "decision — so no applicability date is stated here. Re-run "
                 "with `--route annex_i` or `--route annex_iii` once the "
                 "provider has recorded its determination.")
    L.append("")
    L.append(f"As at {app.as_at}, the Annex IV documentation duty is "
             f"**{'in force' if app.in_force_now else 'not yet applicable'}**. "
             + app.note.strip())
    L.append("")
    if app.anomaly_flagged:
        L.append(f"*Noted as read, not as advice:* {app.anomaly_flagged.strip()}")
        L.append("")

    # ── completion summary ───────────────────────────────────────────────
    L.append("## Completion summary")
    L.append("")
    L.append("| Measure | Value |")
    L.append("|---|---|")
    L.append(f"| Sections addressed | {c.sections_addressed} / {c.sections_total} |")
    L.append(f"| Claims total | {c.claims_total} |")
    L.append(f"| Claims backed by evidence | {c.claims_evidence_backed} "
             f"({100 * c.evidence_backed_ratio:.1f}%) |")
    L.append(f"| Claims flagged as gaps | {c.claims_gapped} |")
    L.append(f"| Citations — MEASURED | {c.citations_measured} |")
    L.append(f"| Citations — ATTESTED | {c.citations_attested} |")
    L.append(f"| MEASURED share of citations | {100 * c.measured_share:.1f}% |")
    L.append(f"| Gaps in the register | {c.gaps_total} "
             f"({c.gaps_permanent} permanent) |")
    L.append("")
    L.append("Every claim below carries either a citation or a gap reference. "
             "There is no third kind of sentence in this document: the claim "
             "type has no constructor for an unsupported assertion.")
    L.append("")

    # ── section state table ──────────────────────────────────────────────
    L.append("| # | Section | State | Claims | Gapped |")
    L.append("|---|---|---|---|---|")
    for s in pack.sections:
        L.append(f"| {s.number} | {s.title} | {_STATE_LABEL[s.state]} | "
                 f"{s.claim_count} | {len(s.gapped)} |")
    L.append("")

    # ── the sections ─────────────────────────────────────────────────────
    gap_by_id = pack.gap_by_id()
    for s in pack.sections:
        spec_section = spec.section(s.number)
        L.append(f"## {s.number}. {s.title}")
        L.append("")
        L.append(f"> {spec_section.text}")
        L.append("")
        if spec_section.article_refs:
            L.append(f"*Cross-references in the annex text:* "
                     f"{', '.join(spec_section.article_refs)}")
            L.append("")
        if spec_section.limbs_are_our_decomposition and spec_section.limbs:
            L.append("*The Official Journal prints this point as a single "
                     "unlettered block. The breakdown below is this tool's "
                     "decomposition for evidence-mapping purposes, not a "
                     "structure the regulation defines.*")
            L.append("")
        if spec_section.ojeu_oddity:
            L.append(f"*Note on the published text:* "
                     f"{spec_section.ojeu_oddity.strip()}")
            L.append("")

        for claim in s.claims:
            head = (f"**{s.number}({claim.subpoint})**"
                    if claim.subpoint and claim.subpoint not in ("whole",)
                    else f"**{s.number}**")
            L.append(f"{head} — {claim.text}")
            L.append("")
            if claim.is_gap:
                g = gap_by_id[claim.gap_id]
                L.append(f"- **GAP** (`{g.id}`, {_KIND_LABEL[g.kind]}"
                         f"{', permanent' if g.permanent else ''}): {g.reason}")
                L.append(f"  - *To close it:* {g.remediation}")
            else:
                for line in _cite(pack, claim):
                    L.append(f"- {line}")
            L.append("")

    # ── gap register ─────────────────────────────────────────────────────
    L.append("## Gap register")
    L.append("")
    if not pack.gaps:
        L.append("No gaps. Every requirement in the mapping spec is backed by "
                 "evidence in the repository.")
    else:
        L.append(f"{len(pack.gaps)} gap(s). These are the sentences this pack "
                 "does **not** make. A template would have written them anyway.")
        L.append("")
        L.append("| Gap | Section | Requirement | Kind | Why |")
        L.append("|---|---|---|---|---|")
        for g in pack.gaps:
            req = g.requirement if len(g.requirement) < 90 else \
                g.requirement[:87].rstrip() + "…"
            where = f"{g.section}({g.subpoint})" if g.subpoint and \
                g.subpoint != "whole" else str(g.section)
            L.append(f"| `{g.id}` | {where} | {req} | "
                     f"{_KIND_LABEL[g.kind]} | {g.reason} |")
    L.append("")

    # ── evidence index ───────────────────────────────────────────────────
    L.append("## Evidence index")
    L.append("")
    L.append("| Id | Class | Source | Hash | Extractor | Attested by |")
    L.append("|---|---|---|---|---|---|")
    for r in pack.evidence:
        loc = f"#{r.locator}" if r.locator else ""
        who = (f"{r.attested_by} ({r.role}), {r.date}"
               if r.cls is EvidenceClass.ATTESTED else "—")
        L.append(f"| `{r.id}` | {r.cls.value} | `{r.source_path}{loc}` | "
                 f"`{r.source_sha256[:12]}…` | {r.extractor} | {who} |")
    L.append("")
    L.append("Every row is re-resolved by `annexiv audit`, which walks this "
             "pack independently of the generator that produced it: the thing "
             "that writes must not be the thing that approves.")
    L.append("")
    L.append("---")
    L.append("")
    L.append(BOUNDARY_STATEMENT)
    L.append("")
    return "\n".join(L)
